/********************************************************************************
 * This class is the Wrapper class for CRONeX VisualForce Component.
 *
 * Description: 
 *              This class acts as Wrapper. It is used for the purpose of 
 * passing cron string from component to the page's controller where it is used.
 *
 * Revision History: 
 *
 * Version     Author               Date         Description 
 * 1.0         Abdulrahim Mulla     10/14/2016   All Basic Functionality Achieved 
 * 
 *
 *********************************************************************************/
public class CronWrapper{
    public String value {get; set;}
}// commit